spring:
  application:
    name: gateway-service

  # Configuration avancée de Spring Cloud Gateway
  cloud:
    gateway:
      # Activation de la découverte de services
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Routes explicites pour chaque microservice
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

        - id: billing-service
          uri: lb://BILLING-SERVICE
          predicates:
            - Path=/billing-service/**
          filters:
            - StripPrefix=1

        - id: cars-service
          uri: lb://CARS-SERVICE
          predicates:
            - Path=/cars-service/**
          filters:
            - StripPrefix=1

        - id: workshop-service
          uri: lb://WORKSHOP-SERVICE
          predicates:
            - Path=/workshop-service/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

server:
  port: 8888

