apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/auth-service-db
        - name: EUREKA_HOST
          value: discovery-service
        - name: EUREKA_PORT
          value: "8761"
        - name: HOSTNAME
          value: auth-service
        - name: IPADDR
          value: auth-service
        - name: JWT_EXPIRES_IN
          value: 24h
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP