apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: customer-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: customer_db
        - name: DB_USERNAME
          value: nom_utilisateur
        - name: DB_PASSWORD
          value: mot_de_passe
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: SPRING_CLOUD_DISCOVERY_ENABLED
          value: "true"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-service:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP